#!/usr/bin/env python3
"""
Build the Enrollment Tracker dashboard.

Reads the source workbook, injects all data into template.html,
and writes index.html for GitHub Pages.

Usage:  python build_dashboard.py
"""

import json
import re
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).parent
README = ROOT / "README.md"
COVERAGE_START = "<!-- COVERAGE:START -->"
COVERAGE_END = "<!-- COVERAGE:END -->"
WORKBOOK = ROOT / "data" / "Enrollment_Tracker.xlsx"
PDF_HISTORY = ROOT / "data" / "pdf_history.json"
COST_SHARING = ROOT / "data" / "cost_sharing.csv"
MEDICARE = ROOT / "data" / "medicare.json"
# Employer-Sponsored Insurance (ESI) staged aggregates — each written from the
# committed source files in source-data/ (Census ACS/CPS, AHRQ MEPS-IC, KFF EHBS)
# by the one-off inspection/staging step, never read from source at build time.
# ACS/CPS count covered PERSONS; MEPS counts enrolled EMPLOYEES (rates + dollars
# only, no counts) — different units, kept in separate files, never blended.
ESI_ACS_CSV = ROOT / "data" / "esi_coverage_acs.csv"
ESI_CPS_CSV = ROOT / "data" / "esi_coverage_cps.csv"
ESI_MEPS_CSV = ROOT / "data" / "esi_cost_meps.csv"
ESI_KFF_CSV = ROOT / "data" / "esi_benchmark_kff.csv"
TEMPLATE = ROOT / "template.html"
OUTPUT = ROOT / "index.html"

# Benefit year of the ACA cost-sharing PUFs feeding data/cost_sharing.csv
# (regenerated by build_cost_sharing.py when a new PUF is published).
CS_BENEFIT_YEAR = "2026"

# Marketplace tabs: "Marketplace (2)" supersedes "Marketplace"
MKT_SHEET = "Marketplace (2)"

# March 2023 pre-unwinding peak enrollment baseline (reference point, not a
# series). Total Medicaid enrollment only — the sheet has no adult or renewal
# breakout, so no adult/renewal code path may read from it.
PEAK_SHEET = "Mcaid Peak Baseline"
PEAK_LABEL = "Mar 2023"

# CHIP is a SEPARATE population from Medicaid (Medicaid-expansion CHIP, separate
# CHIP, and pregnant adults in separate CHIP), not a Medicaid subset. Both CHIP
# sheets use the compact 3-column layout (State, Reporting Period, Total CHIP
# Enrollment) — total enrollment only, no adult or renewal breakout. The
# California and Nevada Medicaid adjustments do NOT apply to CHIP.
CHIP_SHEET = "CHIP"
CHIP_PEAK_SHEET = "CHIP Peak Baseline"
CHIP_PEAK_LABEL = "Mar 2023"

# Medicaid child enrollment is NOT published directly by CMS in the Performance
# Indicator data. It is DERIVED, per state per month, as
#   Medicaid child = (Medicaid and CHIP Child Enrollment) − (Total CHIP Enrollment)
# both of which the CHIP / CHIP Peak Baseline sheets carry. A derived value <= 0
# (or a missing input) means the state did NOT report the child breakout that
# month — not that it has no child enrollment — and is rendered as a gap, never
# as a number. CMS's "Medicaid and CHIP Child Enrollment" also includes pregnant
# adult women in separate CHIP, so the derived figure is not purely children; the
# arithmetic reconciles exactly but the label is imprecise (see CLAUDE.md).
CHIP_TOTAL_COL = "Total CHIP Enrollment"
CHIP_MCCHILD_BOTH_COL = "Medicaid and CHIP Child Enrollment"
# National derived Medicaid-child control totals from the CMS PDF state tables.
# The recent months are checked exactly; older months are revised over time (the
# workbook is the authoritative later vintage — e.g. New Hampshire's March CHIP
# resubmission), so a small delta from the point-in-time PDF is expected, not an
# error.
CHIP_CHILD_CONTROL = {"2026-05": 28_080_687, "2026-04": 28_235_643,
                      "2026-03": 28_358_130}
# Months checked as hard failures: those whose workbook vintage still matches the
# CMS PDF exactly. Older months drift as states resubmit (March carries New
# Hampshire's CHIP revision), so they only emit a note.
CHIP_CHILD_CONTROL_STRICT = {"2026-05", "2026-04"}
# Arizona did not report the Medicaid adult/child breakout from Feb 2020 through
# Apr 2024, so its Mar 2023 peak child figure is unreal (Total CHIP > combined
# child ⇒ negative). Its per-state child peak comparison is suppressed, and the
# national child peak is built from reported states only (Arizona excluded from
# both endpoints). Arizona's post-May-2024 monthly values are valid and display
# normally.

STATE_ABBR = {
    'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas', 'CA': 'California',
    'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware', 'DC': 'District of Columbia',
    'FL': 'Florida', 'GA': 'Georgia', 'HI': 'Hawaii', 'ID': 'Idaho', 'IL': 'Illinois',
    'IN': 'Indiana', 'IA': 'Iowa', 'KS': 'Kansas', 'KY': 'Kentucky', 'LA': 'Louisiana',
    'ME': 'Maine', 'MD': 'Maryland', 'MA': 'Massachusetts', 'MI': 'Michigan',
    'MN': 'Minnesota', 'MS': 'Mississippi', 'MO': 'Missouri', 'MT': 'Montana',
    'NE': 'Nebraska', 'NV': 'Nevada', 'NH': 'New Hampshire', 'NJ': 'New Jersey',
    'NM': 'New Mexico', 'NY': 'New York', 'NC': 'North Carolina', 'ND': 'North Dakota',
    'OH': 'Ohio', 'OK': 'Oklahoma', 'OR': 'Oregon', 'PA': 'Pennsylvania',
    'RI': 'Rhode Island', 'SC': 'South Carolina', 'SD': 'South Dakota', 'TN': 'Tennessee',
    'TX': 'Texas', 'UT': 'Utah', 'VT': 'Vermont', 'VA': 'Virginia', 'WA': 'Washington',
    'WV': 'West Virginia', 'WI': 'Wisconsin', 'WY': 'Wyoming',
}

MCAID_COLS = {
    'enroll': 'Total Medicaid Enrollment',
    'adult': 'Total Medicaid Adult Enrollment',
    'due': 'Beneficiaries with a Renewal Due',
    'renewed': 'Beneficiaries Whose Coverage Was Renewed (Total)',
    'exparte': 'Beneficiaries Whose Coverage Was Renewed on an Ex Parte Basis',
    'form': 'Beneficiaries Whose Coverage Was Renewed based on a Renewal Form',
    'disenrolled': 'Beneficiaries Disenrolled at Renewal (Total)',
    'ineligible': 'Beneficiaries Determined Ineligible at Renewal',
    'procedural': 'Beneficiaries Disenrolled for Procedural Reasons at Renewal',
    'pending': 'Beneficiaries with a Pending Renewal',
}

# California revised its Medicaid reporting in March 2026 to exclude
# limited-benefit enrollees and did not restate prior months, which makes March
# onward non-comparable to earlier months and inflates the apparent national
# decline. We put the whole series on the revised (exclude-limited-benefit)
# basis by restating the PRE-revision months DOWN, rather than inflating the
# post-revision months up. This keeps March 2026 and every later month exactly
# as CMS reports them, so the current/most-recent figures still tie to CMS
# control totals (e.g. national April 66,725,217); only the shrinking pre-March
# tail is an estimate. The two framings produce an identical trend -- they differ
# only by a uniform level shift -- so the choice is purely which end stays real.
# Magnitude: California's average monthly change over Dec 2025-Feb 2026 was
# -106,996 total and -78,132 adult; treating that as the expected March change
# and attributing the excess decline to the reclassification gives the amounts
# below (expected March value minus the value California actually reported),
# i.e. the estimated limited-benefit population removed. These are estimates,
# not CMS figures. Enrollment counts only -- renewal fields are never touched.
# CA_ADJUST_FROM is the first revised (exclude-basis) month; months before it are
# restated down by the constants below.
CA_ADJUST_FROM = '2026-03'
CA_ENROLL_ADJUST = 384186
CA_ADULT_ADJUST = 372782

MKT_COLS = {
    'total': 'Number of Consumers with an Exchange Plan Selection',
    'new': 'New Consumers', 'reenroll': 'Total Re-enrollees',
    'active': 'Active Re-enrollees', 'auto': 'Automatic Re-enrollees',
    'aptc': 'Consumers with APTC', 'avgPrem': 'Average Premium  ',
    'avgNet': 'Average Premium after APTC  ', 'cat': 'Catastrophic',
    'bronze': 'Bronze', 'silver': 'Silver ', 'gold': 'Gold', 'platinum': 'Platinum',
}

# The national (United States) post-OEP Marketplace series is limited to reported
# effectuated months. CMS reported national effectuated totals only through
# February 2026: the workbook has no March figure, and the April value
# (19,200,000) is a rounded placeholder, not a reported count. Publishing them
# would render a misleading isolated dot on the national trend line, so we
# explicitly exclude March 2026 onward for the United States series only. State
# series are unaffected — 12 states report genuine March, April, and May figures.
NATIONAL_POST_OEP_EXCLUDE_FROM = pd.Timestamp('2026-03-01')


def to_int(v):
    return None if pd.isna(v) else int(v)


def normalize_dc(name):
    return 'District of Columbia' if name.strip().lower() == 'district of columbia' else name.strip()


def mix_percentages(rec):
    """Five renewal outcomes as percentages of renewals due, rescaled to sum to exactly 100."""
    parts = [rec['exparte'], rec['form'], rec['ineligible'], rec['procedural'], rec['pending']]
    pcts = [p / rec['due'] * 100 for p in parts]
    total = sum(pcts)
    return [round(p / total * 100, 1) for p in pcts]


def apply_california_adjustment(periods, national, states):
    """Continuity restatement for California's March 2026 reporting revision.

    Restates California's own enrollment counts for the months BEFORE
    CA_ADJUST_FROM down onto the revised exclude-limited-benefit basis, leaving
    CA_ADJUST_FROM and later exactly as CMS reports them, then re-derives the
    national enrollment counts from state totals so the national row stays the
    exact sum of states. Renewal fields are left untouched. Raises if the
    national == sum-of-states identity does not hold on the raw data.
    """
    def sum_states(key, field):
        return sum(s[key][field] for s in states.values()
                   if key in s and s[key][field] is not None)

    for key in periods:
        for field in ('enroll', 'adult'):
            if national[key][field] != sum_states(key, field):
                sys.exit(f"ERROR: national {field} != sum of states at {key}; "
                         "cannot re-derive national after California adjustment")

    ca = states.get('California', {})
    for key in periods:
        if key < CA_ADJUST_FROM and key in ca:
            ca[key]['enroll'] -= CA_ENROLL_ADJUST
            ca[key]['adult'] -= CA_ADULT_ADJUST
            national[key]['enroll'] = sum_states(key, 'enroll')
            national[key]['adult'] = sum_states(key, 'adult')


def load_medicaid(xl):
    df = pd.read_excel(xl, sheet_name="Mcaid")
    df['State'] = df['State'].astype(str).map(normalize_dc)
    df['P'] = pd.to_datetime(df['Reporting Period'])
    df['key'] = df['P'].dt.strftime('%Y-%m')

    periods = sorted(df['key'].unique())
    labels = [pd.Timestamp(p + '-01').strftime('%b %Y') for p in periods]

    states, national = {}, {}
    for _, row in df.iterrows():
        rec = {k: to_int(row[c]) for k, c in MCAID_COLS.items()}
        if row['State'] == 'United States':
            national[row['key']] = rec
        else:
            states.setdefault(row['State'], {})[row['key']] = rec

    apply_california_adjustment(periods, national, states)

    # Top 12 states by disenrollment rate in the most recent month
    latest = periods[-1]
    recent = df[(df['key'] == latest) & (df['State'] != 'United States')].copy()
    recent['rate'] = recent[MCAID_COLS['disenrolled']] / recent[MCAID_COLS['due']]
    top = recent.nlargest(12, 'rate')
    top12 = {
        'labels': list(top['State']),
        'rates': [round(r * 100, 1) for r in top['rate']],
        'disen': [int(v) for v in top[MCAID_COLS['disenrolled']]],
        'due': [int(v) for v in top[MCAID_COLS['due']]],
    }
    return periods, labels, latest, national, states, top12


def load_peak_baseline(xl):
    """March 2023 pre-unwinding peak TOTAL Medicaid enrollment by state + US.

    Returns {stateName|'United States': peak_total}. This is a reference point,
    NOT a trend series — it is never added to MCAID_PERIODS or any series. The
    sheet carries total enrollment only (no adult, no renewal fields), so nothing
    here feeds an adult- or renewal-enrollment path. The March 2023 baseline
    predates California's reporting revision, so California's peak still includes
    the limited-benefit enrollees its current figure excludes; the current-side
    California continuity adjustment only partly offsets that, and the peak strip
    discloses the residual non-comparability rather than restating the peak.
    """
    if PEAK_SHEET not in xl.sheet_names:
        sys.exit(f"ERROR: '{PEAK_SHEET}' sheet missing from workbook")
    df = pd.read_excel(xl, sheet_name=PEAK_SHEET)
    df['State'] = df['State'].astype(str).map(normalize_dc)
    peak = {row['State']: to_int(row['Total Medicaid Enrollment']) for _, row in df.iterrows()}

    states_sum = sum(v for k, v in peak.items() if k != 'United States' and v is not None)
    if peak.get('United States') != states_sum:
        sys.exit(f"ERROR: peak baseline United States {peak.get('United States')} "
                 f"!= sum of states {states_sum}")
    return peak


def load_chip(xl):
    """CHIP total enrollment by state + US, one value per state per month.

    CHIP is a separate population from Medicaid, so no Medicaid adjustment
    (California continuity, Nevada caveat) applies here. The sheet carries total
    CHIP enrollment only — there is no adult or renewal breakout. Verifies the
    national United States row equals the exact sum of states in every period;
    gaps (a state missing a month) are preserved as None so the trend renders a
    gap rather than interpolating.
    """
    if CHIP_SHEET not in xl.sheet_names:
        sys.exit(f"ERROR: '{CHIP_SHEET}' sheet missing from workbook")
    df = pd.read_excel(xl, sheet_name=CHIP_SHEET)
    df['State'] = df['State'].astype(str).map(normalize_dc)
    df['P'] = pd.to_datetime(df['Reporting Period'])
    df['key'] = df['P'].dt.strftime('%Y-%m')

    periods = sorted(df['key'].unique())
    labels = [pd.Timestamp(p + '-01').strftime('%b %Y') for p in periods]

    states, national = {}, {}
    for _, row in df.iterrows():
        val = to_int(row['Total CHIP Enrollment'])
        if row['State'] == 'United States':
            national[row['key']] = val
        else:
            states.setdefault(row['State'], {})[row['key']] = val

    for p in periods:
        states_sum = sum(s[p] for s in states.values()
                         if p in s and s[p] is not None)
        if national.get(p) != states_sum:
            sys.exit(f"ERROR: CHIP national {national.get(p)} != sum of states "
                     f"{states_sum} at {p}")

    latest = periods[-1]
    return periods, labels, latest, national, states


def load_chip_peak_baseline(xl):
    """March 2023 pre-unwinding peak TOTAL CHIP enrollment by state + US.

    Returns {stateName|'United States': peak_total}. Like the Medicaid peak, this
    is a reference point, NOT a trend series — it is never added to CHIP_PERIODS
    or any series. Total CHIP enrollment only. Verifies the United States row
    equals the sum of states.
    """
    if CHIP_PEAK_SHEET not in xl.sheet_names:
        sys.exit(f"ERROR: '{CHIP_PEAK_SHEET}' sheet missing from workbook")
    df = pd.read_excel(xl, sheet_name=CHIP_PEAK_SHEET)
    df['State'] = df['State'].astype(str).map(normalize_dc)
    peak = {row['State']: to_int(row['Total CHIP Enrollment']) for _, row in df.iterrows()}

    states_sum = sum(v for k, v in peak.items() if k != 'United States' and v is not None)
    if peak.get('United States') != states_sum:
        sys.exit(f"ERROR: CHIP peak baseline United States {peak.get('United States')} "
                 f"!= sum of states {states_sum}")
    return peak


def derive_child(both, chip):
    """DERIVED Medicaid child = (Medicaid and CHIP child) − Total CHIP.

    Returns None when the breakout was not reported — a missing input, or a
    derived value <= 0 (Total CHIP >= combined child means the state reported
    CHIP but not the Medicaid/CHIP child split that month). A None renders as a
    gap on the dashboard; a derived value is never allowed to be negative or zero.
    """
    if both is None or chip is None:
        return None
    d = both - chip
    return d if d > 0 else None


def load_chip_child(xl):
    """Derived Medicaid child enrollment by state + US, one value per month.

    Not a CMS-published series — derived from the CHIP sheet's two child columns
    via derive_child (see the module note). Returns (national, states) parallel
    to load_chip; states that did not report the breakout in a month carry None
    (rendered as a gap, never zero). The national row is validated as the exact
    sum of reported states in every period, and against the CMS PDF state-table
    control totals in CHIP_CHILD_CONTROL.
    """
    if CHIP_SHEET not in xl.sheet_names:
        sys.exit(f"ERROR: '{CHIP_SHEET}' sheet missing from workbook")
    df = pd.read_excel(xl, sheet_name=CHIP_SHEET)
    df['State'] = df['State'].astype(str).map(normalize_dc)
    df['P'] = pd.to_datetime(df['Reporting Period'])
    df['key'] = df['P'].dt.strftime('%Y-%m')
    periods = sorted(df['key'].unique())

    states, national = {}, {}
    for _, row in df.iterrows():
        val = derive_child(to_int(row[CHIP_MCCHILD_BOTH_COL]),
                           to_int(row[CHIP_TOTAL_COL]))
        if row['State'] == 'United States':
            national[row['key']] = val
        else:
            states.setdefault(row['State'], {})[row['key']] = val

    for p in periods:
        states_sum = sum(s[p] for s in states.values()
                         if s.get(p) is not None)
        if national.get(p) != states_sum:
            sys.exit(f"ERROR: derived Medicaid child national {national.get(p)} "
                     f"!= sum of reported states {states_sum} at {p}")

    for p, ctrl in CHIP_CHILD_CONTROL.items():
        got = national.get(p)
        if got is None or got == ctrl:
            continue
        if p in CHIP_CHILD_CONTROL_STRICT:
            sys.exit(f"ERROR: derived Medicaid child national {p} = {got} "
                     f"!= CMS control {ctrl}")
        print(f"  note: derived Medicaid child national {p} = {got:,} vs "
              f"CMS PDF {ctrl:,} (delta {got - ctrl:+,}; revised vintage)")

    return national, states


def load_chip_child_peak(xl):
    """March 2023 peak DERIVED Medicaid child enrollment by state + US.

    Reference point only, never a trend series (mirrors load_chip_peak_baseline).
    Per state, derived via derive_child; a state that did not report the child
    breakout in Mar 2023 carries None and its child peak comparison is suppressed
    on the dashboard. Arizona sits inside its Feb 2020-Apr 2024 non-reporting
    window, so its derived peak is negative -> None. The national child peak is
    the sum of REPORTED states only, i.e. Arizona is excluded from both endpoints
    (the current national child endpoint is likewise reduced by Arizona in the JS
    so the comparison stays like-for-like; a per-tab note discloses this).
    """
    if CHIP_PEAK_SHEET not in xl.sheet_names:
        sys.exit(f"ERROR: '{CHIP_PEAK_SHEET}' sheet missing from workbook")
    df = pd.read_excel(xl, sheet_name=CHIP_PEAK_SHEET)
    df['State'] = df['State'].astype(str).map(normalize_dc)

    peak = {}
    for _, row in df.iterrows():
        if row['State'] == 'United States':
            continue
        peak[row['State']] = derive_child(to_int(row[CHIP_MCCHILD_BOTH_COL]),
                                          to_int(row[CHIP_TOTAL_COL]))
    peak['United States'] = sum(v for v in peak.values() if v is not None)
    return peak


def load_chip_both(xl):
    """Reported 'Medicaid and CHIP Child Enrollment' (the combined child column)
    by state + US, one value per month.

    This is the raw reported column — the sum of Total CHIP and derived Medicaid
    child — surfaced as a top-panel KPI alongside its two components. Not a
    derivation and no adjustment applies. Validated as the exact sum of reported
    states each month, and (as a cross-check) that it equals Total CHIP + derived
    Medicaid child on the national row.
    """
    if CHIP_SHEET not in xl.sheet_names:
        sys.exit(f"ERROR: '{CHIP_SHEET}' sheet missing from workbook")
    df = pd.read_excel(xl, sheet_name=CHIP_SHEET)
    df['State'] = df['State'].astype(str).map(normalize_dc)
    df['P'] = pd.to_datetime(df['Reporting Period'])
    df['key'] = df['P'].dt.strftime('%Y-%m')
    periods = sorted(df['key'].unique())

    states, national = {}, {}
    for _, row in df.iterrows():
        val = to_int(row[CHIP_MCCHILD_BOTH_COL])
        if row['State'] == 'United States':
            national[row['key']] = val
        else:
            states.setdefault(row['State'], {})[row['key']] = val

    for p in periods:
        states_sum = sum(s[p] for s in states.values() if s.get(p) is not None)
        if national.get(p) != states_sum:
            sys.exit(f"ERROR: Medicaid+CHIP child national {national.get(p)} "
                     f"!= sum of states {states_sum} at {p}")
    return national, states


def build_mix(periods, labels, national, states):
    """Renewal outcome mix. National blends PDF history (Mar-Nov 2025) with workbook data."""
    hist = json.loads(PDF_HISTORY.read_text())
    keys = ['exparte', 'form', 'inelig', 'proc', 'pend']

    nat = {k: list(hist[k]) for k in keys}
    nat_labels = list(hist['labels'])
    for p, lab in zip(periods, labels):
        e, f, i, pr, pe = mix_percentages(national[p])
        nat_labels.append(lab)
        for k, v in zip(keys, [e, f, i, pr, pe]):
            nat[k].append(v)
    nat['labels'] = nat_labels

    st = {}
    for name, by_period in states.items():
        series = {k: [] for k in keys}
        for p in periods:
            rec = by_period.get(p)
            vals = mix_percentages(rec) if rec else [None] * 5
            for k, v in zip(keys, vals):
                series[k].append(v)
        st[name] = series

    return {'natLabels': nat_labels, 'nat': nat, 'stLabels': labels, 'states': st}


def load_marketplace(xl):
    df = pd.read_excel(xl, sheet_name=MKT_SHEET)
    df['State'] = df['State'].astype(str).map(normalize_dc)
    for col in MKT_COLS.values():
        df[col] = pd.to_numeric(df[col], errors='coerce')

    oep_rows = df[df['Reporting Period'] == 'OEP']
    oep, national_oep = {}, None
    for _, row in oep_rows.iterrows():
        rec = {k: (0 if pd.isna(row[c]) else int(row[c])) for k, c in MKT_COLS.items()}
        rec['plat'] = rec.pop('platinum')
        if row['State'] == 'United States':
            national_oep = rec
        elif rec['total'] > 0:
            oep[row['State']] = rec

    dated = df[df['Reporting Period'] != 'OEP'].copy()
    dated['P'] = pd.to_datetime(dated['Reporting Period'])
    months = sorted(dated['P'].unique())
    labels = ['OEP'] + [pd.Timestamp(m).strftime('%b') for m in months]

    series = {}
    for name in list(oep) + ['United States']:
        sub = dated[dated['State'] == name].set_index('P')
        base = national_oep if name == 'United States' else oep[name]
        vals = [base['total']]
        for m in months:
            # National post-OEP data is limited to reported months (through Feb 2026);
            # exclude the missing/placeholder March-onward values for United States only.
            if name == 'United States' and pd.Timestamp(m) >= NATIONAL_POST_OEP_EXCLUDE_FROM:
                vals.append(None)
            else:
                vals.append(to_int(sub.loc[m, MKT_COLS['total']]) if m in sub.index else None)
        if any(v is not None for v in vals[1:]):
            series[name] = vals

    return oep, national_oep, labels, series


def load_effectuated(xl):
    df = pd.read_excel(xl, sheet_name="Marketplace Feb. Effec. Enroll")
    df['S'] = df['State'].astype(str).str.strip().map(
        lambda s: 'United States' if s == 'United States' else STATE_ABBR.get(s, s))
    df['E'] = pd.to_numeric(df['Effectuated Enrollment'], errors='coerce')

    out = {}
    for name, group in df.groupby('S'):
        vals = {f"{int(r['Year'])}-{r['Month'][:3]}": to_int(r['E']) for _, r in group.iterrows()}
        out[name] = {'jan25': vals.get('2025-Jan'), 'feb25': vals.get('2025-Feb'),
                     'jan26': vals.get('2026-Jan'), 'feb26': vals.get('2026-Feb')}
    return out


def load_cost_sharing():
    """Read data/cost_sharing.csv into {stateName|'United States': {tier: {...}}}.

    Keyed by full state name to match the Marketplace state selector (which
    passes full names). States absent here (full SBE states not in the PUF, e.g.
    California, New York) simply have no entry and the card shows a no-data note.
    """
    import csv as _csv

    if not COST_SHARING.exists():
        sys.exit(f"ERROR: cost-sharing data not found at {COST_SHARING}; "
                 "run build_cost_sharing.py first")

    def num(v):
        return None if v is None or v == "" else int(v)

    out = {}
    with COST_SHARING.open(newline="", encoding="utf-8") as f:
        for row in _csv.DictReader(f):
            code = row["State"]
            name = "United States" if code == "United States" else STATE_ABBR.get(code, code)
            out.setdefault(name, {})[row["MetalTier"]] = {
                "ded": num(row["AvgDeductible"]),
                "oop": num(row["AvgOOPMax"]),
                "copay": num(row["AvgPrimaryCareCopay"]),
            }
    return out


def load_medicare():
    """Read data/medicare.json — the small per-state monthly Medicare summary.

    Written by build_medicare.py from the raw CMS Medicare Monthly Enrollment
    file (in source-data/); the monthly dashboard rebuild only reads this
    aggregate and never touches the raw source. The national series here is the
    sum of the 50 states + DC (territories excluded), so it runs below CMS's
    published national — see build_medicare.py and CLAUDE.md for the scope
    decision. Returns the parsed object as-is for injection.
    """
    if not MEDICARE.exists():
        sys.exit(f"ERROR: Medicare data not found at {MEDICARE}; "
                 "run build_medicare.py first")
    mc = json.loads(MEDICARE.read_text())
    n = mc["national"][mc["latest"]]
    if n["org"] + n["ma"] != n["tot"]:
        sys.exit("ERROR: Medicare national Original+MA != Total; rebuild medicare.json")
    return mc


# BHP participants, in the fixed top-to-bottom display order used by the KPI row and
# the state-share strip. Only DC, MN, NY, OR participate (see CLAUDE.md). Colours and
# layout live in template.html; every volatile FIGURE below is computed here so a
# monthly workbook drop needs no hand-editing of the markup.
BHP_STATE_ORDER = ['New York', 'Minnesota', 'Oregon', 'District of Columbia']


def _bhp_range(vals, labels):
    """Per-state chart-card subtitle: 'Reported Jan – Aug 2026', or
    'Reported Jan 2026 only' when a state has a single reported month."""
    idx = [i for i, v in enumerate(vals) if v is not None]
    first, last = labels[idx[0]], labels[idx[-1]]
    return f"Reported {first} only" if first == last else f"Reported {first} &ndash; {last}"


def _bhp_coverage(byState, nat_month_long, n_states):
    """Generate the coverage-caveat sentence (HTML) from each state's reported range,
    grouping states that report through the same month. Self-updating: no month or
    state name is hand-written in the template."""
    def bold(name):
        return f'<b style="color:#5A4A1A">{name}</b>'

    multi, single = [], []
    for name in BHP_STATE_ORDER:
        d = byState[name]
        (single if d['nMonths'] == 1 else multi).append(name)

    clauses = []
    # multi-month states grouped by their last reported month, most recent first
    groups = {}
    for name in multi:
        groups.setdefault(byState[name]['last'], []).append(name)
    for last in sorted(groups, key=lambda l: byState[groups[l][0]]['lastIdx'], reverse=True):
        names = groups[last]
        joined = names[0] if len(names) == 1 else ' and '.join(
            [', '.join(bold(n) for n in names[:-1]), bold(names[-1])] if len(names) > 2
            else [bold(n) for n in names])
        if len(names) == 1:
            joined = bold(names[0])
        verb = 'report' if len(names) > 1 else 'reports'
        clauses.append(f'{joined} {verb} through {last}')
    for name in single:
        clauses.append(f'{bold(name)} has reported {byState[name]["last"]} only')

    return (f'Reporting coverage varies. {"; ".join(clauses)}. National total reflects '
            f'{nat_month_long}, the most recent month all {n_states} states report.')


def load_bhp(xl):
    df = pd.read_excel(xl, sheet_name="BHP")
    df['State'] = df['State'].astype(str).map(normalize_dc)
    df['P'] = pd.to_datetime(df['Reporting Period'])
    df['v'] = pd.to_numeric(df['BHP Enrollment'], errors='coerce')

    months = sorted(df['P'].unique())
    labels = [pd.Timestamp(m).strftime('%b %Y') for m in months]
    labels_long = [pd.Timestamp(m).strftime('%B %Y') for m in months]
    series = {}
    for name, group in df[df['State'] != 'United States'].groupby('State'):
        g = group.set_index('P')
        series[name] = [to_int(g.loc[m, 'v']) if m in g.index else None for m in months]

    participants = [s for s in BHP_STATE_ORDER if s in series]
    if set(participants) != set(series):
        sys.exit(f"ERROR: BHP sheet has unexpected states {sorted(set(series) - set(participants))}; "
                 "add them to BHP_STATE_ORDER (with colours in template.html) before building")

    # National figure = the most recent month in which EVERY participant reports (DC,
    # which reports only January, caps this today). Different measures otherwise.
    nat_idx = [i for i in range(len(months))
               if all(series[s][i] is not None for s in participants)]
    if not nat_idx:
        sys.exit("ERROR: no BHP month has all participating states reporting; national total undefined")
    ni = nat_idx[-1]
    nat_total = sum(series[s][ni] for s in participants)

    # Cross-check against the workbook's own United States row when it is populated.
    us = df[df['State'] == 'United States'].set_index('P')['v']
    us_val = to_int(us.get(months[ni])) if months[ni] in us.index else None
    if us_val is not None and us_val != nat_total:
        sys.exit(f"ERROR: BHP United States row {us_val:,} != sum of states {nat_total:,} "
                 f"for {labels[ni]}")

    byState = {}
    for name in participants:
        vals = series[name]
        idx = [i for i, v in enumerate(vals) if v is not None]
        byState[name] = {
            'val': vals[ni],
            'pct': vals[ni] / nat_total * 100,
            'range': _bhp_range(vals, labels),
            'first': labels[idx[0]], 'last': labels[idx[-1]], 'lastIdx': idx[-1],
            'nMonths': len(idx),
        }
    top = max(participants, key=lambda s: byState[s]['val'])

    kpi = {
        'natTotal': nat_total,
        'natMonth': labels[ni],
        'natMonthLong': labels_long[ni],
        'nStates': len(participants),
        'byState': byState,
        'top': {'name': top, 'pct': byState[top]['pct']},
        'coverage': _bhp_coverage(byState, labels_long[ni], len(participants)),
    }
    return labels, series, kpi


def load_esi_acs():
    """Read data/esi_coverage_acs.csv -> ({state|'United States': persons}, year).

    ACS employment-based coverage counts COVERED PERSONS at time of interview
    (a single survey year). Point-in-time measure; never combined with the MEPS
    enrolled-employee figures or the CPS calendar-year counts.
    """
    import csv as _csv
    if not ESI_ACS_CSV.exists():
        sys.exit(f"ERROR: ESI ACS data not found at {ESI_ACS_CSV}")
    out, year = {}, None
    with ESI_ACS_CSV.open(newline="", encoding="utf-8") as f:
        for row in _csv.DictReader(f):
            out[row["State"]] = int(row["CoveredPersons"])
            year = int(row["Year"])
    # National row must be present and match the sum of states within ACS's
    # independent rounding (values are published rounded to the nearest 1,000).
    if "United States" not in out:
        sys.exit("ERROR: ESI ACS missing United States row")
    ssum = sum(v for s, v in out.items() if s != "United States")
    if abs(out["United States"] - ssum) > 50_000:
        sys.exit(f"ERROR: ESI ACS US {out['United States']:,} != sum of states {ssum:,}")
    return out, year


def load_esi_cps():
    """Read data/esi_coverage_cps.csv -> [[year, persons], ...] (national only).

    CPS ASEC employment-based coverage counts COVERED PERSONS during the prior
    calendar year — a different reference period from ACS, so the two national
    totals differ for the same nominal year (expected, not an error). This is the
    only real ESI time series; state data is single-year and cross-sectional.
    """
    import csv as _csv
    if not ESI_CPS_CSV.exists():
        sys.exit(f"ERROR: ESI CPS data not found at {ESI_CPS_CSV}")
    rows = []
    with ESI_CPS_CSV.open(newline="", encoding="utf-8") as f:
        for row in _csv.DictReader(f):
            rows.append([int(row["Year"]), int(row["CoveredPersons"])])
    rows.sort()
    return rows


# MEPS-IC CSV columns -> compact JS keys. Rates (percent) and dollars only; no
# enrolled-employee count is carried (counts come from ACS). Both offer-rate
# denominators are kept distinct: 'ofe' = % of establishments that offer,
# 'ofm' = % of employees at establishments that offer — different metrics.
ESI_MEPS_COLS = {
    "OfferRate_Estab_pct": "ofe",
    "OfferRate_Emp_pct": "ofm",
    "Eligible_pct_of_emp_at_offering": "elig",
    "TakeUp_pct_of_eligible": "take",
    "Enrolled_pct_of_emp_at_offering": "enr",
    "SinglePremium_USD": "ps",
    "SingleContribution_USD": "cs",
    "FamilyPremium_USD": "pf",
    "FamilyContribution_USD": "cf",
    "SingleDeductible_USD": "ds",
    "FamilyDeductible_USD": "df",
}


def load_esi_meps(acs_states):
    """Read data/esi_cost_meps.csv -> ({state|'United States': {key: value}}, year).

    MEPS-IC private-sector Table II — excludes state and local government. Counts
    enrolled EMPLOYEES (one worker covering a family is a single enrollee), a
    different unit from the ACS/CPS person counts. Single-year, so state views are
    cross-sectional only. `acs_states` is passed in to assert the two sources cover
    the same jurisdictions before either is wired to the shared state selector.
    """
    import csv as _csv
    if not ESI_MEPS_CSV.exists():
        sys.exit(f"ERROR: ESI MEPS data not found at {ESI_MEPS_CSV}")

    def num(v):
        return None if v is None or v == "" else float(v)

    out, year = {}, None
    with ESI_MEPS_CSV.open(newline="", encoding="utf-8") as f:
        for row in _csv.DictReader(f):
            rec = {}
            for col, key in ESI_MEPS_COLS.items():
                x = num(row[col])
                rec[key] = int(x) if x is not None and x == int(x) else x
            out[row["State"]] = rec
            year = int(row["Year"])
    if "United States" not in out:
        sys.exit("ERROR: ESI MEPS missing United States row")
    meps_states = {s for s in out if s != "United States"}
    if meps_states != set(acs_states):
        only_m = sorted(meps_states - set(acs_states))
        only_a = sorted(set(acs_states) - meps_states)
        sys.exit(f"ERROR: ESI MEPS/ACS jurisdictions differ; MEPS-only={only_m} ACS-only={only_a}")
    return out, year


def load_esi_kff():
    """Read data/esi_benchmark_kff.csv -> compact national-benchmark dict.

    KFF EHBS is NATIONAL only and a survey-based benchmark for the current year —
    it must never populate a state view and is never charted as the national
    series (CPS is the series). Pulls the headline current-year values used by the
    benchmark card; the raw CSV is retained for provenance.
    """
    import csv as _csv
    if not ESI_KFF_CSV.exists():
        sys.exit(f"ERROR: ESI KFF data not found at {ESI_KFF_CSV}")
    rows = list(_csv.DictReader(ESI_KFF_CSV.open(newline="", encoding="utf-8")))
    if not rows:
        sys.exit("ERROR: ESI KFF benchmark is empty")
    year = str(max(int(r["Year"]) for r in rows))

    def pick(metric, coverage):
        for r in rows:
            if r["Year"] == year and r["Metric"] == metric and r["Coverage"] == coverage:
                return int(r["Value"])
        return None

    kff = {
        "year": int(year),
        "premSingle": pick("Average annual premium", "Single"),
        "premFamily": pick("Average annual premium", "Family"),
        "wcSingle": pick("Worker premium contribution", "Single"),
        "wcFamily": pick("Worker premium contribution", "Family"),
        "shareSingle": pick("Worker contribution share", "Single"),
        "shareFamily": pick("Worker contribution share", "Family"),
        "dedSingle": pick("Average general annual deductible", "Single"),
    }
    missing = [k for k, v in kff.items() if v is None]
    if missing:
        sys.exit(f"ERROR: ESI KFF benchmark missing {year} values: {missing}")
    return kff


def state_pills(prefix, fn, names):
    out = [f'<button class="state-pill active" onclick="{fn}(null)" id="{prefix}-btn-national">National</button>']
    for s in sorted(names):
        sid = s.replace(' ', '-').replace('.', '')
        out.append(f'<button class="state-pill" onclick="{fn}(\'{s}\')" id="{prefix}-btn-{sid}">{s}</button>')
    return '\n      '.join(out)


def update_readme_coverage(rows):
    """Splice an auto-generated coverage table into README.md between the COVERAGE
    markers, so the published date ranges track the data instead of drifting by hand.
    No-op if README.md or the markers are absent (build never fails on this)."""
    if not README.exists():
        return
    text = README.read_text()
    if COVERAGE_START not in text or COVERAGE_END not in text:
        return
    table = ["| Domain | Source | Coverage |", "|---|---|---|"]
    table += [f"| {d} | {s} | {c} |" for d, s, c in rows]
    block = (f"{COVERAGE_START}\n"
             "<!-- auto-generated by build_dashboard.py — do not edit by hand -->\n\n"
             + "\n".join(table) + f"\n\n{COVERAGE_END}")
    new = re.sub(re.escape(COVERAGE_START) + ".*?" + re.escape(COVERAGE_END),
                 lambda _: block, text, flags=re.S)
    if new != text:
        README.write_text(new)


def main():
    if not WORKBOOK.exists():
        sys.exit(f"ERROR: workbook not found at {WORKBOOK}")

    xl = pd.ExcelFile(WORKBOOK)
    periods, labels, latest, mc_nat, mc_states, top12 = load_medicaid(xl)
    mix = build_mix(periods, labels, mc_nat, mc_states)
    peak = load_peak_baseline(xl)
    chip_periods, chip_labels, chip_latest, chip_nat, chip_states = load_chip(xl)
    chip_peak = load_chip_peak_baseline(xl)
    chip_child_nat, chip_child_states = load_chip_child(xl)
    chip_child_peak = load_chip_child_peak(xl)
    chip_both_nat, chip_both_states = load_chip_both(xl)
    mkt_oep, mkt_nat, post_labels, post_series = load_marketplace(xl)
    yoy = load_effectuated(xl)
    cost_sharing = load_cost_sharing()
    bhp_labels, bhp_series, bhp_kpi = load_bhp(xl)
    medicare = load_medicare()
    esi_acs, esi_acs_year = load_esi_acs()
    esi_cps = load_esi_cps()
    esi_acs_states = [s for s in esi_acs if s != 'United States']
    esi_meps, esi_meps_year = load_esi_meps(esi_acs_states)
    esi_kff = load_esi_kff()

    compact = lambda o: json.dumps(o, separators=(',', ':'))
    replacements = {
        'MCAID_PILLS': state_pills('mcaid', 'selectMcaidState', mc_states),
        'CHIP_PILLS': state_pills('chip', 'selectChipState', chip_states),
        'MKT_PILLS': state_pills('mkt', 'selectMktState', mkt_oep),
        'MCARE_PILLS': state_pills('mcare', 'selectMcareState', medicare['states']),
        '__MCAID_PERIODS__': compact(periods),
        '__MCAID_LABELS__': compact(labels),
        '__MCAID_LATEST__': compact(latest),
        '__MCAID_NAT__': compact(mc_nat),
        '__MCAID_STATES__': compact(mc_states),
        '__TOP12__': compact(top12),
        '__MIX__': compact(mix),
        '__MCAID_PEAK__': compact(peak),
        '__PEAK_LABEL__': compact(PEAK_LABEL),
        '__CHIP_PERIODS__': compact(chip_periods),
        '__CHIP_LABELS__': compact(chip_labels),
        '__CHIP_LATEST__': compact(chip_latest),
        '__CHIP_NAT__': compact(chip_nat),
        '__CHIP_STATES__': compact(chip_states),
        '__CHIP_PEAK__': compact(chip_peak),
        '__CHIP_PEAK_LABEL__': compact(CHIP_PEAK_LABEL),
        '__CHIP_CHILD_NAT__': compact(chip_child_nat),
        '__CHIP_CHILD_STATES__': compact(chip_child_states),
        '__CHIP_CHILD_PEAK__': compact(chip_child_peak),
        '__CHIP_BOTH_NAT__': compact(chip_both_nat),
        '__CHIP_BOTH_STATES__': compact(chip_both_states),
        '__MKT_OEP__': compact(mkt_oep),
        '__MKT_NAT_OEP__': compact(mkt_nat),
        '__POST_LABELS__': compact(post_labels),
        '__POST_OEP__': compact(post_series),
        '__YOY__': compact(yoy),
        '__COST_SHARING__': compact(cost_sharing),
        '__CS_YEAR__': compact(CS_BENEFIT_YEAR),
        '__BHP_LABELS__': compact(bhp_labels),
        '__BHP_SERIES__': compact(bhp_series),
        '__BHP_NAT_TOTAL__': f"{bhp_kpi['natTotal']:,}",
        '__BHP_NAT_MONTH__': bhp_kpi['natMonth'],
        '__BHP_NAT_MONTH_LONG__': bhp_kpi['natMonthLong'],
        '__BHP_N_STATES__': str(bhp_kpi['nStates']),
        '__BHP_COVERAGE__': bhp_kpi['coverage'],
        '__BHP_TOP_STATE__': bhp_kpi['top']['name'],
        '__BHP_TOP_PCT__': f"{bhp_kpi['top']['pct']:.1f}",
        '__MEDICARE__': compact(medicare),
        'ESI_PILLS': state_pills('esi', 'selectEsiState', esi_acs_states),
        '__ESI_ACS__': compact(esi_acs),
        '__ESI_ACS_YEAR__': compact(esi_acs_year),
        '__ESI_CPS__': compact(esi_cps),
        '__ESI_MEPS__': compact(esi_meps),
        '__ESI_MEPS_YEAR__': compact(esi_meps_year),
        '__ESI_KFF__': compact(esi_kff),
    }

    for st, sid in (('New York', 'NY'), ('Minnesota', 'MN'),
                    ('Oregon', 'OR'), ('District of Columbia', 'DC')):
        d = bhp_kpi['byState'][st]
        replacements[f'__BHP_{sid}_VAL__'] = f"{d['val']:,}"
        replacements[f'__BHP_{sid}_PCT__'] = f"{d['pct']:.1f}"
        replacements[f'__BHP_{sid}_RANGE__'] = d['range']

    html = TEMPLATE.read_text()
    for placeholder, value in replacements.items():
        html = html.replace(placeholder, value)

    leftover = [p for p in replacements if p in html]
    if leftover:
        sys.exit(f"ERROR: unsubstituted placeholders: {leftover}")

    OUTPUT.write_text(html)

    update_readme_coverage([
        ("Medicaid", "CMS Medicaid &amp; CHIP Enrollment Snapshot",
         f"{labels[0]} – {labels[-1]}"),
        ("CHIP &amp; Medicaid Child", "CMS Medicaid &amp; CHIP Enrollment Snapshot",
         f"{chip_labels[0]} – {chip_labels[-1]}"),
        ("National renewal outcome mix", "CMS snapshot PDF (Mar–Nov 2025) + workbook",
         f"{mix['natLabels'][0]} – {mix['natLabels'][-1]}"),
        ("BHP", "CMS Basic Health Program",
         f"{bhp_labels[0]} – {bhp_labels[-1]} (national total: {bhp_kpi['natMonth']})"),
        ("ACA Marketplace", "CMS Marketplace OEP snapshot + effectuated enrollment",
         f"OEP 2026 + effectuated through {post_labels[-1]} 2026"),
        ("Medicare", "CMS Medicare Monthly Enrollment",
         f"{medicare['labels'][0]} – {medicare['labels'][-1]}"),
        ("ACA cost sharing", "CMS Exchange PUFs (Plan Attributes; Benefits &amp; Cost-Sharing)",
         f"{CS_BENEFIT_YEAR} benefit year"),
        ("Employer coverage (ESI)", "Census ACS/CPS · AHRQ MEPS-IC · KFF EHBS",
         f"ACS {esi_acs_year} · MEPS-IC {esi_meps_year}"),
    ])

    print(f"Built {OUTPUT.name}  ({len(html) // 1024} KB)")
    print(f"  Medicaid    {labels[0]} - {labels[-1]}  ({len(mc_states)} states)")
    print(f"  Peak base   {PEAK_LABEL} pre-unwinding  ({len([s for s in peak if s != 'United States'])} states + US)")
    print(f"  CHIP        {chip_labels[0]} - {chip_labels[-1]}  ({len(chip_states)} states)  "
          f"{chip_labels[-1]} national {chip_nat[chip_latest]:,}")
    print(f"  CHIP peak   {CHIP_PEAK_LABEL} pre-unwinding  "
          f"({len([s for s in chip_peak if s != 'United States'])} states + US)")
    _az = chip_child_states.get('Arizona', {}).get(chip_latest)
    print(f"  Mcaid child (derived)  {chip_labels[-1]} national {chip_child_nat[chip_latest]:,}  "
          f"({sum(1 for s in chip_child_states.values() if s.get(chip_latest) is not None)} states reporting)")
    print(f"    child peak {CHIP_PEAK_LABEL} national {chip_child_peak['United States']:,} "
          f"(Arizona excluded, both endpoints; AZ peak={chip_child_peak.get('Arizona')})")
    print(f"  Mcaid+CHIP child (reported)  {chip_labels[-1]} national {chip_both_nat[chip_latest]:,} "
          f"(= CHIP {chip_nat[chip_latest]:,} + child {chip_child_nat[chip_latest]:,})")
    print(f"  BHP         {bhp_labels[0]} - {bhp_labels[-1]}  ({len(bhp_series)} states)")
    mc_now = medicare['national'][medicare['latest']]
    print(f"  Medicare    {medicare['labels'][0]} - {medicare['labels'][-1]}  "
          f"({len(medicare['states'])} states + DC, territories excluded)  "
          f"{medicare['labels'][-1]} MA penetration {mc_now['ma']/mc_now['abtot']*100:.1f}% (of A&B)")
    print(f"  Marketplace OEP + {len(post_labels) - 1} months  ({len(mkt_oep)} states)")
    cs_states = [s for s in cost_sharing if s != 'United States']
    print(f"  Cost sharing {CS_BENEFIT_YEAR} plan-level avg  ({len(cs_states)} states + US)")
    print(f"  ESI ACS     {esi_acs_year} covered persons  ({len(esi_acs_states)} states + US)  "
          f"US {esi_acs['United States']:,}")
    print(f"  ESI CPS     {esi_cps[0][0]}–{esi_cps[-1][0]} national covered persons  "
          f"({esi_cps[-1][0]} {esi_cps[-1][1]:,}; ACS–CPS {esi_acs_year} gap "
          f"{esi_acs['United States']-dict(esi_cps).get(esi_acs_year,0):+,})")
    print(f"  ESI MEPS    {esi_meps_year} private-sector rates+dollars  ({len(esi_acs_states)} states + US)  "
          f"US single prem ${esi_meps['United States']['ps']:,}")
    print(f"  ESI KFF     {esi_kff['year']} national benchmark (survey; not the national series)")
    print(f"  Outcome mix {mix['natLabels'][0]} - {mix['natLabels'][-1]} national, "
          f"{mix['stLabels'][0]} - {mix['stLabels'][-1]} by state")


if __name__ == "__main__":
    main()
