#!/usr/bin/env python3
"""
Build the Enrollment Tracker dashboard.

Reads the source workbook, injects all data into template.html,
and writes index.html for GitHub Pages.

Usage:  python build_dashboard.py
"""

import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).parent
WORKBOOK = ROOT / "data" / "Enrollment_Tracker.xlsx"
PDF_HISTORY = ROOT / "data" / "pdf_history.json"
COST_SHARING = ROOT / "data" / "cost_sharing.csv"
TEMPLATE = ROOT / "template.html"
OUTPUT = ROOT / "index.html"

# Benefit year of the ACA cost-sharing PUFs feeding data/cost_sharing.csv
# (regenerated by build_cost_sharing.py when a new PUF is published).
CS_BENEFIT_YEAR = "2026"

# Marketplace tabs: "Marketplace (2)" supersedes "Marketplace"
MKT_SHEET = "Marketplace (2)"

# March 2023 pre-unwinding peak enrollment baseline (reference point, not a
# series). Total Medicaid enrollment only — the sheet has no adult or renewal
# breakout, so no adult/renewal code path may read from it.
PEAK_SHEET = "Mcaid Peak Baseline"
PEAK_LABEL = "Mar 2023"

# CHIP is a SEPARATE population from Medicaid (Medicaid-expansion CHIP, separate
# CHIP, and pregnant adults in separate CHIP), not a Medicaid subset. Both CHIP
# sheets use the compact 3-column layout (State, Reporting Period, Total CHIP
# Enrollment) — total enrollment only, no adult or renewal breakout. The
# California and Nevada Medicaid adjustments do NOT apply to CHIP.
CHIP_SHEET = "CHIP"
CHIP_PEAK_SHEET = "CHIP Peak Baseline"
CHIP_PEAK_LABEL = "Mar 2023"

STATE_ABBR = {
    'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas', 'CA': 'California',
    'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware', 'DC': 'District of Columbia',
    'FL': 'Florida', 'GA': 'Georgia', 'HI': 'Hawaii', 'ID': 'Idaho', 'IL': 'Illinois',
    'IN': 'Indiana', 'IA': 'Iowa', 'KS': 'Kansas', 'KY': 'Kentucky', 'LA': 'Louisiana',
    'ME': 'Maine', 'MD': 'Maryland', 'MA': 'Massachusetts', 'MI': 'Michigan',
    'MN': 'Minnesota', 'MS': 'Mississippi', 'MO': 'Missouri', 'MT': 'Montana',
    'NE': 'Nebraska', 'NV': 'Nevada', 'NH': 'New Hampshire', 'NJ': 'New Jersey',
    'NM': 'New Mexico', 'NY': 'New York', 'NC': 'North Carolina', 'ND': 'North Dakota',
    'OH': 'Ohio', 'OK': 'Oklahoma', 'OR': 'Oregon', 'PA': 'Pennsylvania',
    'RI': 'Rhode Island', 'SC': 'South Carolina', 'SD': 'South Dakota', 'TN': 'Tennessee',
    'TX': 'Texas', 'UT': 'Utah', 'VT': 'Vermont', 'VA': 'Virginia', 'WA': 'Washington',
    'WV': 'West Virginia', 'WI': 'Wisconsin', 'WY': 'Wyoming',
}

MCAID_COLS = {
    'enroll': 'Total Medicaid Enrollment',
    'adult': 'Total Medicaid Adult Enrollment',
    'due': 'Beneficiaries with a Renewal Due',
    'renewed': 'Beneficiaries Whose Coverage Was Renewed (Total)',
    'exparte': 'Beneficiaries Whose Coverage Was Renewed on an Ex Parte Basis',
    'form': 'Beneficiaries Whose Coverage Was Renewed based on a Renewal Form',
    'disenrolled': 'Beneficiaries Disenrolled at Renewal (Total)',
    'ineligible': 'Beneficiaries Determined Ineligible at Renewal',
    'procedural': 'Beneficiaries Disenrolled for Procedural Reasons at Renewal',
    'pending': 'Beneficiaries with a Pending Renewal',
}

# California revised its Medicaid reporting in March 2026 to exclude
# limited-benefit enrollees and did not restate prior months, which makes March
# onward non-comparable to earlier months and inflates the apparent national
# decline. We put the whole series on the revised (exclude-limited-benefit)
# basis by restating the PRE-revision months DOWN, rather than inflating the
# post-revision months up. This keeps March 2026 and every later month exactly
# as CMS reports them, so the current/most-recent figures still tie to CMS
# control totals (e.g. national April 66,725,217); only the shrinking pre-March
# tail is an estimate. The two framings produce an identical trend -- they differ
# only by a uniform level shift -- so the choice is purely which end stays real.
# Magnitude: California's average monthly change over Dec 2025-Feb 2026 was
# -106,996 total and -78,132 adult; treating that as the expected March change
# and attributing the excess decline to the reclassification gives the amounts
# below (expected March value minus the value California actually reported),
# i.e. the estimated limited-benefit population removed. These are estimates,
# not CMS figures. Enrollment counts only -- renewal fields are never touched.
# CA_ADJUST_FROM is the first revised (exclude-basis) month; months before it are
# restated down by the constants below.
CA_ADJUST_FROM = '2026-03'
CA_ENROLL_ADJUST = 384186
CA_ADULT_ADJUST = 372782

MKT_COLS = {
    'total': 'Number of Consumers with an Exchange Plan Selection',
    'new': 'New Consumers', 'reenroll': 'Total Re-enrollees',
    'active': 'Active Re-enrollees', 'auto': 'Automatic Re-enrollees',
    'aptc': 'Consumers with APTC', 'avgPrem': 'Average Premium  ',
    'avgNet': 'Average Premium after APTC  ', 'cat': 'Catastrophic',
    'bronze': 'Bronze', 'silver': 'Silver ', 'gold': 'Gold', 'platinum': 'Platinum',
}

# The national (United States) post-OEP Marketplace series is limited to reported
# effectuated months. CMS reported national effectuated totals only through
# February 2026: the workbook has no March figure, and the April value
# (19,200,000) is a rounded placeholder, not a reported count. Publishing them
# would render a misleading isolated dot on the national trend line, so we
# explicitly exclude March 2026 onward for the United States series only. State
# series are unaffected — 12 states report genuine March, April, and May figures.
NATIONAL_POST_OEP_EXCLUDE_FROM = pd.Timestamp('2026-03-01')


def to_int(v):
    return None if pd.isna(v) else int(v)


def normalize_dc(name):
    return 'District of Columbia' if name.strip().lower() == 'district of columbia' else name.strip()


def mix_percentages(rec):
    """Five renewal outcomes as percentages of renewals due, rescaled to sum to exactly 100."""
    parts = [rec['exparte'], rec['form'], rec['ineligible'], rec['procedural'], rec['pending']]
    pcts = [p / rec['due'] * 100 for p in parts]
    total = sum(pcts)
    return [round(p / total * 100, 1) for p in pcts]


def apply_california_adjustment(periods, national, states):
    """Continuity restatement for California's March 2026 reporting revision.

    Restates California's own enrollment counts for the months BEFORE
    CA_ADJUST_FROM down onto the revised exclude-limited-benefit basis, leaving
    CA_ADJUST_FROM and later exactly as CMS reports them, then re-derives the
    national enrollment counts from state totals so the national row stays the
    exact sum of states. Renewal fields are left untouched. Raises if the
    national == sum-of-states identity does not hold on the raw data.
    """
    def sum_states(key, field):
        return sum(s[key][field] for s in states.values()
                   if key in s and s[key][field] is not None)

    for key in periods:
        for field in ('enroll', 'adult'):
            if national[key][field] != sum_states(key, field):
                sys.exit(f"ERROR: national {field} != sum of states at {key}; "
                         "cannot re-derive national after California adjustment")

    ca = states.get('California', {})
    for key in periods:
        if key < CA_ADJUST_FROM and key in ca:
            ca[key]['enroll'] -= CA_ENROLL_ADJUST
            ca[key]['adult'] -= CA_ADULT_ADJUST
            national[key]['enroll'] = sum_states(key, 'enroll')
            national[key]['adult'] = sum_states(key, 'adult')


def load_medicaid(xl):
    df = pd.read_excel(xl, sheet_name="Mcaid")
    df['State'] = df['State'].astype(str).map(normalize_dc)
    df['P'] = pd.to_datetime(df['Reporting Period'])
    df['key'] = df['P'].dt.strftime('%Y-%m')

    periods = sorted(df['key'].unique())
    labels = [pd.Timestamp(p + '-01').strftime('%b %Y') for p in periods]

    states, national = {}, {}
    for _, row in df.iterrows():
        rec = {k: to_int(row[c]) for k, c in MCAID_COLS.items()}
        if row['State'] == 'United States':
            national[row['key']] = rec
        else:
            states.setdefault(row['State'], {})[row['key']] = rec

    apply_california_adjustment(periods, national, states)

    # Top 12 states by disenrollment rate in the most recent month
    latest = periods[-1]
    recent = df[(df['key'] == latest) & (df['State'] != 'United States')].copy()
    recent['rate'] = recent[MCAID_COLS['disenrolled']] / recent[MCAID_COLS['due']]
    top = recent.nlargest(12, 'rate')
    top12 = {
        'labels': list(top['State']),
        'rates': [round(r * 100, 1) for r in top['rate']],
        'disen': [int(v) for v in top[MCAID_COLS['disenrolled']]],
        'due': [int(v) for v in top[MCAID_COLS['due']]],
    }
    return periods, labels, latest, national, states, top12


def load_peak_baseline(xl):
    """March 2023 pre-unwinding peak TOTAL Medicaid enrollment by state + US.

    Returns {stateName|'United States': peak_total}. This is a reference point,
    NOT a trend series — it is never added to MCAID_PERIODS or any series. The
    sheet carries total enrollment only (no adult, no renewal fields), so nothing
    here feeds an adult- or renewal-enrollment path. The March 2023 baseline
    predates California's reporting revision, so California's peak still includes
    the limited-benefit enrollees its current figure excludes; the current-side
    California continuity adjustment only partly offsets that, and the peak strip
    discloses the residual non-comparability rather than restating the peak.
    """
    if PEAK_SHEET not in xl.sheet_names:
        sys.exit(f"ERROR: '{PEAK_SHEET}' sheet missing from workbook")
    df = pd.read_excel(xl, sheet_name=PEAK_SHEET)
    df['State'] = df['State'].astype(str).map(normalize_dc)
    peak = {row['State']: to_int(row['Total Medicaid Enrollment']) for _, row in df.iterrows()}

    states_sum = sum(v for k, v in peak.items() if k != 'United States' and v is not None)
    if peak.get('United States') != states_sum:
        sys.exit(f"ERROR: peak baseline United States {peak.get('United States')} "
                 f"!= sum of states {states_sum}")
    return peak


def load_chip(xl):
    """CHIP total enrollment by state + US, one value per state per month.

    CHIP is a separate population from Medicaid, so no Medicaid adjustment
    (California continuity, Nevada caveat) applies here. The sheet carries total
    CHIP enrollment only — there is no adult or renewal breakout. Verifies the
    national United States row equals the exact sum of states in every period;
    gaps (a state missing a month) are preserved as None so the trend renders a
    gap rather than interpolating.
    """
    if CHIP_SHEET not in xl.sheet_names:
        sys.exit(f"ERROR: '{CHIP_SHEET}' sheet missing from workbook")
    df = pd.read_excel(xl, sheet_name=CHIP_SHEET)
    df['State'] = df['State'].astype(str).map(normalize_dc)
    df['P'] = pd.to_datetime(df['Reporting Period'])
    df['key'] = df['P'].dt.strftime('%Y-%m')

    periods = sorted(df['key'].unique())
    labels = [pd.Timestamp(p + '-01').strftime('%b %Y') for p in periods]

    states, national = {}, {}
    for _, row in df.iterrows():
        val = to_int(row['Total CHIP Enrollment'])
        if row['State'] == 'United States':
            national[row['key']] = val
        else:
            states.setdefault(row['State'], {})[row['key']] = val

    for p in periods:
        states_sum = sum(s[p] for s in states.values()
                         if p in s and s[p] is not None)
        if national.get(p) != states_sum:
            sys.exit(f"ERROR: CHIP national {national.get(p)} != sum of states "
                     f"{states_sum} at {p}")

    latest = periods[-1]
    return periods, labels, latest, national, states


def load_chip_peak_baseline(xl):
    """March 2023 pre-unwinding peak TOTAL CHIP enrollment by state + US.

    Returns {stateName|'United States': peak_total}. Like the Medicaid peak, this
    is a reference point, NOT a trend series — it is never added to CHIP_PERIODS
    or any series. Total CHIP enrollment only. Verifies the United States row
    equals the sum of states.
    """
    if CHIP_PEAK_SHEET not in xl.sheet_names:
        sys.exit(f"ERROR: '{CHIP_PEAK_SHEET}' sheet missing from workbook")
    df = pd.read_excel(xl, sheet_name=CHIP_PEAK_SHEET)
    df['State'] = df['State'].astype(str).map(normalize_dc)
    peak = {row['State']: to_int(row['Total CHIP Enrollment']) for _, row in df.iterrows()}

    states_sum = sum(v for k, v in peak.items() if k != 'United States' and v is not None)
    if peak.get('United States') != states_sum:
        sys.exit(f"ERROR: CHIP peak baseline United States {peak.get('United States')} "
                 f"!= sum of states {states_sum}")
    return peak


def build_mix(periods, labels, national, states):
    """Renewal outcome mix. National blends PDF history (Mar-Nov 2025) with workbook data."""
    hist = json.loads(PDF_HISTORY.read_text())
    keys = ['exparte', 'form', 'inelig', 'proc', 'pend']

    nat = {k: list(hist[k]) for k in keys}
    nat_labels = list(hist['labels'])
    for p, lab in zip(periods, labels):
        e, f, i, pr, pe = mix_percentages(national[p])
        nat_labels.append(lab)
        for k, v in zip(keys, [e, f, i, pr, pe]):
            nat[k].append(v)
    nat['labels'] = nat_labels

    st = {}
    for name, by_period in states.items():
        series = {k: [] for k in keys}
        for p in periods:
            rec = by_period.get(p)
            vals = mix_percentages(rec) if rec else [None] * 5
            for k, v in zip(keys, vals):
                series[k].append(v)
        st[name] = series

    return {'natLabels': nat_labels, 'nat': nat, 'stLabels': labels, 'states': st}


def load_marketplace(xl):
    df = pd.read_excel(xl, sheet_name=MKT_SHEET)
    df['State'] = df['State'].astype(str).map(normalize_dc)
    for col in MKT_COLS.values():
        df[col] = pd.to_numeric(df[col], errors='coerce')

    oep_rows = df[df['Reporting Period'] == 'OEP']
    oep, national_oep = {}, None
    for _, row in oep_rows.iterrows():
        rec = {k: (0 if pd.isna(row[c]) else int(row[c])) for k, c in MKT_COLS.items()}
        rec['plat'] = rec.pop('platinum')
        if row['State'] == 'United States':
            national_oep = rec
        elif rec['total'] > 0:
            oep[row['State']] = rec

    dated = df[df['Reporting Period'] != 'OEP'].copy()
    dated['P'] = pd.to_datetime(dated['Reporting Period'])
    months = sorted(dated['P'].unique())
    labels = ['OEP'] + [pd.Timestamp(m).strftime('%b') for m in months]

    series = {}
    for name in list(oep) + ['United States']:
        sub = dated[dated['State'] == name].set_index('P')
        base = national_oep if name == 'United States' else oep[name]
        vals = [base['total']]
        for m in months:
            # National post-OEP data is limited to reported months (through Feb 2026);
            # exclude the missing/placeholder March-onward values for United States only.
            if name == 'United States' and pd.Timestamp(m) >= NATIONAL_POST_OEP_EXCLUDE_FROM:
                vals.append(None)
            else:
                vals.append(to_int(sub.loc[m, MKT_COLS['total']]) if m in sub.index else None)
        if any(v is not None for v in vals[1:]):
            series[name] = vals

    return oep, national_oep, labels, series


def load_effectuated(xl):
    df = pd.read_excel(xl, sheet_name="Marketplace Feb. Effec. Enroll")
    df['S'] = df['State'].astype(str).str.strip().map(
        lambda s: 'United States' if s == 'United States' else STATE_ABBR.get(s, s))
    df['E'] = pd.to_numeric(df['Effectuated Enrollment'], errors='coerce')

    out = {}
    for name, group in df.groupby('S'):
        vals = {f"{int(r['Year'])}-{r['Month'][:3]}": to_int(r['E']) for _, r in group.iterrows()}
        out[name] = {'jan25': vals.get('2025-Jan'), 'feb25': vals.get('2025-Feb'),
                     'jan26': vals.get('2026-Jan'), 'feb26': vals.get('2026-Feb')}
    return out


def load_cost_sharing():
    """Read data/cost_sharing.csv into {stateName|'United States': {tier: {...}}}.

    Keyed by full state name to match the Marketplace state selector (which
    passes full names). States absent here (full SBE states not in the PUF, e.g.
    California, New York) simply have no entry and the card shows a no-data note.
    """
    import csv as _csv

    if not COST_SHARING.exists():
        sys.exit(f"ERROR: cost-sharing data not found at {COST_SHARING}; "
                 "run build_cost_sharing.py first")

    def num(v):
        return None if v is None or v == "" else int(v)

    out = {}
    with COST_SHARING.open(newline="", encoding="utf-8") as f:
        for row in _csv.DictReader(f):
            code = row["State"]
            name = "United States" if code == "United States" else STATE_ABBR.get(code, code)
            out.setdefault(name, {})[row["MetalTier"]] = {
                "ded": num(row["AvgDeductible"]),
                "oop": num(row["AvgOOPMax"]),
                "copay": num(row["AvgPrimaryCareCopay"]),
            }
    return out


def load_bhp(xl):
    df = pd.read_excel(xl, sheet_name="BHP")
    df['State'] = df['State'].astype(str).map(normalize_dc)
    df['P'] = pd.to_datetime(df['Reporting Period'])
    df['v'] = pd.to_numeric(df['BHP Enrollment'], errors='coerce')

    months = sorted(df['P'].unique())
    labels = [pd.Timestamp(m).strftime('%b %Y') for m in months]
    series = {}
    for name, group in df[df['State'] != 'United States'].groupby('State'):
        g = group.set_index('P')
        series[name] = [to_int(g.loc[m, 'v']) if m in g.index else None for m in months]
    return labels, series


def state_pills(prefix, fn, names):
    out = [f'<button class="state-pill active" onclick="{fn}(null)" id="{prefix}-btn-national">National</button>']
    for s in sorted(names):
        sid = s.replace(' ', '-').replace('.', '')
        out.append(f'<button class="state-pill" onclick="{fn}(\'{s}\')" id="{prefix}-btn-{sid}">{s}</button>')
    return '\n      '.join(out)


def main():
    if not WORKBOOK.exists():
        sys.exit(f"ERROR: workbook not found at {WORKBOOK}")

    xl = pd.ExcelFile(WORKBOOK)
    periods, labels, latest, mc_nat, mc_states, top12 = load_medicaid(xl)
    mix = build_mix(periods, labels, mc_nat, mc_states)
    peak = load_peak_baseline(xl)
    chip_periods, chip_labels, chip_latest, chip_nat, chip_states = load_chip(xl)
    chip_peak = load_chip_peak_baseline(xl)
    mkt_oep, mkt_nat, post_labels, post_series = load_marketplace(xl)
    yoy = load_effectuated(xl)
    cost_sharing = load_cost_sharing()
    bhp_labels, bhp_series = load_bhp(xl)

    compact = lambda o: json.dumps(o, separators=(',', ':'))
    replacements = {
        'MCAID_PILLS': state_pills('mcaid', 'selectMcaidState', mc_states),
        'CHIP_PILLS': state_pills('chip', 'selectChipState', chip_states),
        'MKT_PILLS': state_pills('mkt', 'selectMktState', mkt_oep),
        '__MCAID_PERIODS__': compact(periods),
        '__MCAID_LABELS__': compact(labels),
        '__MCAID_LATEST__': compact(latest),
        '__MCAID_NAT__': compact(mc_nat),
        '__MCAID_STATES__': compact(mc_states),
        '__TOP12__': compact(top12),
        '__MIX__': compact(mix),
        '__MCAID_PEAK__': compact(peak),
        '__PEAK_LABEL__': compact(PEAK_LABEL),
        '__CHIP_PERIODS__': compact(chip_periods),
        '__CHIP_LABELS__': compact(chip_labels),
        '__CHIP_LATEST__': compact(chip_latest),
        '__CHIP_NAT__': compact(chip_nat),
        '__CHIP_STATES__': compact(chip_states),
        '__CHIP_PEAK__': compact(chip_peak),
        '__CHIP_PEAK_LABEL__': compact(CHIP_PEAK_LABEL),
        '__MKT_OEP__': compact(mkt_oep),
        '__MKT_NAT_OEP__': compact(mkt_nat),
        '__POST_LABELS__': compact(post_labels),
        '__POST_OEP__': compact(post_series),
        '__YOY__': compact(yoy),
        '__COST_SHARING__': compact(cost_sharing),
        '__CS_YEAR__': compact(CS_BENEFIT_YEAR),
        '__BHP_LABELS__': compact(bhp_labels),
        '__BHP_SERIES__': compact(bhp_series),
    }

    html = TEMPLATE.read_text()
    for placeholder, value in replacements.items():
        html = html.replace(placeholder, value)

    leftover = [p for p in replacements if p in html]
    if leftover:
        sys.exit(f"ERROR: unsubstituted placeholders: {leftover}")

    OUTPUT.write_text(html)

    print(f"Built {OUTPUT.name}  ({len(html) // 1024} KB)")
    print(f"  Medicaid    {labels[0]} - {labels[-1]}  ({len(mc_states)} states)")
    print(f"  Peak base   {PEAK_LABEL} pre-unwinding  ({len([s for s in peak if s != 'United States'])} states + US)")
    print(f"  CHIP        {chip_labels[0]} - {chip_labels[-1]}  ({len(chip_states)} states)  "
          f"{chip_labels[-1]} national {chip_nat[chip_latest]:,}")
    print(f"  CHIP peak   {CHIP_PEAK_LABEL} pre-unwinding  "
          f"({len([s for s in chip_peak if s != 'United States'])} states + US)")
    print(f"  BHP         {bhp_labels[0]} - {bhp_labels[-1]}  ({len(bhp_series)} states)")
    print(f"  Marketplace OEP + {len(post_labels) - 1} months  ({len(mkt_oep)} states)")
    cs_states = [s for s in cost_sharing if s != 'United States']
    print(f"  Cost sharing {CS_BENEFIT_YEAR} plan-level avg  ({len(cs_states)} states + US)")
    print(f"  Outcome mix {mix['natLabels'][0]} - {mix['natLabels'][-1]} national, "
          f"{mix['stLabels'][0]} - {mix['stLabels'][-1]} by state")


if __name__ == "__main__":
    main()
